---
title: "BoxPlotting"
author: "Lin Crampton"
date: "30Apr2015" 
output: html_document
---
========================================================
#Notchless and Notched
```{r setup4notchless, echo=F}
dataMatrix=matrix(c("A",	-0.54, "A",	-0.8, "A",	-1.03, "A",	-0.41, "A",	-1.31, "A",	-0.66, "A",	-0.43, "A",	1.01, "A",	-1.15, "A",	0.14, "A",	1.42, "A",	-0.3, "A",	-0.16, "A",	0.15, "A",	-0.62, "A",	-0.42, "A",	-0.4, "A",	-0.35, "A",	-0.42, "A",	0.32, "A",	-0.57, "A",	-0.07, "A",	-0.06, "A",	-0.24, "A",	0.02, "A",	-0.39, "A",	-0.74, "A",	-0.92, "A",	-0.09, "A",	-0.03, "A",	0.18, "A",	0.25, "A",	0.48, "A",	-0.39, "A",	-0.24, "A",	-0.3, "A",	0.25, "A",	-0.42, "A",	0.54, "A",	0.03, "A",	-0.66, "A",	0.3, "A",	-0.38, "A",	-0.03, "A",	-0.62, "A",	0.14, "A",	-1.68, "A",	-0.77, "A",	-0.8, "A",	-0.09, "A",	-0.8, "A",	-0.41, "A",	-0.88, "A",	-0.27, "A",	-0.55, "A",	-0.07, "A",	-1.6, "A",	-0.11, "A",	-0.79, "A",	-0.33, "A",	-1.26, "A",	1.31, "A",	-0.33, "A",	-0.43, "A",	-0.92, "A",	-0.11, "A",	-0.29, "A",	-1.02, "A",	0.41, "A",	-0.81, "A",	0.61, "A",	-0.63, "A",	-0.49, "A",	0.18, "A",	0.17, "A",	0.24, "A",	0.13, "A",	-0.12, "A",	-0.24, "A",	-0.26, "A",	1.48, "A",	0.04, "A",	0.81, "A",	-0.56, "A",	-1.12, "A",	-0.19, "A",	0.27, "A",	-1.28, "A",	-0.38, "A",	-0.83, "A",	0.25, "A",	-0.14, "A",	0.45, "A",	0.29, "A",	0.18, "A",	0.74, "A",	0.44, "A",	-0.28, "A",	-0.31, "A",	0.08, "A",	-0.18, "A",	-0.29, "A",	-0.62, "A",	-0.08, "A",	-0.87, "A",	0.19, "A",	0.54, "A",	0.34, "A",	0.54, "A",	-0.35, "A",	0.02, "A",	-0.39, "A",	0.38, "A",	1.25, "A",	-0.51, "A",	-0.39, "A",	0.05, "A",	-0.36, "A",	-0.19, "A",	-1.49, "A",	-0.1, "A",	0.08, "A",	-1.16, "A",	-0.77, "A",	1.58, "A",	-0.92, "A",	0.59, "A",	-0.35, "A",	0.26, "A",	-0.78, "A",	1.2, "A",	0.06, "A",	-0.68, "A",	-0.19, "A",	-0.44, "A",	0.56, "A",	0.93, "A",	-0.35, "A",	0.11, "A",	-0.22, "A",	-0.12, "A",	-0.22, "A",	0.29, "B",	-0.67, "B",	-0.77, "B",	-0.03, "B",	-0.12, "B",	-0.57, "B",	-0.76, "B",	0.19, "B",	-1.8, "B",	0.35, "B",	-0.81, "B",	1.8, "B",	-0.99, "B",	-2.22, "B",	-1.06, "B",	-0.69, "B",	0.06, "B",	-0.2, "B",	-1.68, "B",	-0.64, "B",	-0.44, "B",	0.29, "B",	-0.13, "B",	-1.98, "B",	-0.84, "B",	0.44, "B",	0, "B",	-1.32, "B",	-0.54, "B",	-0.05, "B",	-0.54, "B",	0.23, "B",	0.38, "B",	0.35, "B",	-0.61, "B",	0.3, "B",	-0.33, "B",	0.79, "B",	-1.39, "B",	-0.06, "B",	-0.88, "B",	0.44, "B",	0.32, "B",	-0.45, "B",	0.21, "B",	0.2, "B",	-2.03, "B",	0.59, "B",	-0.78, "B",	-0.92, "B",	-0.96, "B",	-0.1, "B",	-0.07, "B",	0.39, "B",	-0.39, "B",	-1.11, "B",	-0.98, "B",	-0.11, "B",	-1.78, "B",	-0.73, "B",	-1.01, "B",	-0.5, "B",	-0.16, "B",	-0.59, "B",	-1.46, "B",	1.13, "B",	1.01, "B",	1, "B",	0.21, "B",	-0.21, "B",	-1.05, "B",	-1.34, "B",	-0.72, "B",	-0.47, "B",	0.1, "B",	0.15, "C",	1.67, "C",	0.81, "C",	-1.81, "C",	-1.18, "C",	0.49, "C",	-1.74, "C",	-1.57, "C",	0.46, "C",	1.31, "C",	0.16, "C",	-0.39, "C",	-0.4, "C",	0.44, "C",	1.18, "C",	-2.08, "C",	-1.62, "C",	-0.3, "C",	-1.53, "C",	0.03, "C",	-0.42, "C",	-1.91, "C",	-1.86, "C",	-1.99, "C",	-0.25, "C",	-1.14, "C",	-2.11, "C",	-0.93, "C",	0.42, "C",	-1.13, "C",	0.13, "C",	-0.92, "C",	-0.34, "C",	0.38, "C",	-2.01, "C",	1.42, "C",	0.1, "C",	-0.44, "C",	-2.17, "C",	0.13, "C",	-1.75, "C",	0.52, "C",	-1.18, "C",	0.85, "C",	1.11, "C",	0.64, "C",	0.97, "C",	-0.72, "C",	-0.04, "C",	0.38, "C",	-1.87, "C",	-0.89, "C",	-2.09, "C",	-1.54, "C",	-0.17, "C",	0.09, "C",	-0.25, "C",	0.51, "C",	0.33, "C",	-1.29, "C",	-0.51, "C",	-1.62, "C",	-0.5, "C",	-0.52), ncol=2,byrow=T, dimnames=list(c(),c("subtype", "expression")))
dataFrame = as.data.frame(dataMatrix, col.names=c('subtype','expression'), stringsAsFactors=F)
A = as.numeric(dataFrame[which(dataFrame$subtype=="A"),2])
B = as.numeric(dataFrame[which(dataFrame$subtype=="B"),2])
C = as.numeric(dataFrame[which(dataFrame$subtype=="C"),2])
```
Default notchless boxplot
```{r notchlessBoxPlot}
boxplot(A,B,C,col=c("red","green","blue"), names=c("A","B","C"),  xlab="Subtype",ylab="Expression")

#When the 'notch' parameter is 'TRUE', a notch is drawn in each side of the boxes. When notches of two plots do not overlap, tis strong evidence that the two medians differ.
boxplot(A,B,C,col=c("red","green","blue"),names=c("A","B","C"), notch=TRUE, xlab="Subtype",ylab="Expression")
```
========================================================

```{r diamondSetup, results="hide", echo=F}
### loading all packages that you need for your code to work in one go
libs <- c('ggplot2', 'latticeExtra', 'gridExtra', 'MASS', 
          'colorspace', 'plyr', 'Hmisc', 'scales')
lapply(libs, require, character.only = T)

### load the diamonds data set (comes with ggplot2)
data(diamonds)
bw.ggplot <- ggplot(diamonds, aes(x = color, y = price))
#g.bw <- bw.ggplot + geom_boxplot()
#print(g.bw)
```
#Adding Faceting
```{r facetedDiamonds}
bw.ggplot <- ggplot(diamonds, aes(x = color, y = price))

g.bw <- bw.ggplot + 
  geom_boxplot(fill = "grey90") +
  theme_bw() +
  facet_wrap(~ cut)

print(g.bw)
```
========================================================
#Adding Color
Add color to make it a wee bit less of a sporific
```{r coloredDiamonds}
w <- sqrt(table(diamonds$color)/nrow(diamonds))
### standardise w to maximum value
w <- w / max(w)
clrs.spec <- colorRampPalette(rev(brewer.pal(11, "Spectral")))
clrs.hcl <- function(n) {
  hcl(h = seq(230, 0, length.out = n), 
      c = 60, l = seq(10, 90, length.out = n), 
      fixup = TRUE)
  }

g.bw <- bw.ggplot + 
  facet_wrap(~ cut) +
  llply(unique(diamonds$color), 
        function(i) geom_boxplot(fill = clrs.hcl(7)[i],
                                 width = w[i], outlier.shape = "*",
                                 outlier.size = 3,
                                 data = subset(diamonds, color == i))) +
  theme_bw()

print(g.bw)
```
========================================================
