---
title: "dplyr - EdX"
author: "Lin Crampton"
date: "19 Apr 2015"
output: html_document
---
Clean up environment, load and examine/plot statesMap mercator 
```{r initialize}
rm(list=ls())
setwd('~/EdX/AE')
library('downloader')
url = "https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/msleep_ggplot2.csv"
filename = "msleep_ggplot2.csv"
if (!file.exists(filename)) download(url,filename)
  msleep = read.csv("msleep_ggplot2.csv")
head(msleep)
```
Selecting w dplyr
```{r dplyrSelect}
library('dplyr')
# select columns name, sleep_total
sleepData = select(msleep, name, sleep_total)
#select all columns except name
head(select(msleep, -name, -order, -sleep_rem))
#select columns starting with 'sl'
head(select(msleep, starts_with("sl"))) 
# or ends_with(charStr), contains(charStr), matches(regEx), one_of(groupOfNames)
```
Filtering
```{r dplyrFilter}
# mammals that sleep +16 hrs
filter(msleep, sleep_total >= 16) 
# mammals sleep +16hrs & bodywt .ge. 1
filter(msleep, sleep_total >=16, bodywt >=1)
# mammals in specific taxonomy
filter(msleep, order %in% c("Perissodactyla", "Primates"))
```
Piping
```{r dplyrPiping}
#use pipes like Unix
msleep %>% select(name, sleep_total) %>% head
```
Arrange 
```{r dplyrArrange}
#arrange by taxonomic order and secondarily by sleep_total
msleep %>%
	select(name, order, sleep_total) %>%
	arrange(order, sleep_total) %>%
	head
# arrange taxonomic order and secondarily and decendenly by sleep_total and take only slep_total ~16
msleep %>%
	select(name, order, sleep_total) %>%
	arrange(order, desc(sleep_total)) %>%
	filter(sleep_total >=16)
```
Create new columns
```{r dplyrMutate}
# new col - ratio of REM sleep to total sleep
msleep %>%
	mutate(rem_proportion = sleep_rem / sleep_total) %>%
	head
# two new cols - rem_proportion and bodywt_grams
msleep %>%
	mutate(rem_proportio = sleep_rem / sleep_total,
		bodywt_grams = bodywt * 1000) %>%
	head
```
Summarise
```{r dplyrSummarise}
# summarise sleep_total
msleep %>%
	summarise(avg_sleep = mean(sleep_total))
msleep %>%
	summarise(	avg_sleep = mean(sleep_total),
			min_sleep = min(sleep_total),
			max_sleep = max(sleep_total),
			total = n()) #n = length of vector
```
Grouping - Split a data frame, apply function to resulting individual data frames, then recombine
```{r dplyrGroup_by}
#split by taxonomic order, average, and return
msleep %>% 
    group_by(order) %>%
    summarise(avg_sleep = mean(sleep_total), 
              min_sleep = min(sleep_total), 
              max_sleep = max(sleep_total),
              total = n())
```
Add column REM/total sleep (REMprop), group by taxonomic order, summarise by median REMprop, arrange by median REMprop.
```{r dplyrKitchenSink}
msleep %>%
  mutate(REMprop = sleep_rem / sleep_total) %>%
  group_by(order) %>%
  summarise(meanREM = mean(REMprop)) %>%
  arrange(meanREM) %>%
  head
```